import feedparser
import requests
import os
import asyncio
from playwright.async_api import async_playwright # Kept for completeness, not used
import google.generativeai as genai
import json # For parsing Gemini's response

# Configure Gemini API Key
try:
    GOOGLE_API_KEY = os.environ['GOOGLE_API_KEY']
    genai.configure(api_key=GOOGLE_API_KEY)
    print("Gemini API Key configured.")
except KeyError:
    print("Error: GOOGLE_API_KEY environment variable not set. Gemini features will be disabled.")
    GOOGLE_API_KEY = None
except Exception as e:
    print(f"Error configuring Gemini: {e}. Gemini features will be disabled.")
    GOOGLE_API_KEY = None


def get_yahoo_finance_news_rss() -> list[dict[str, str]]:
    """
    Fetches and parses news headlines from Yahoo Finance RSS feed.
    Returns a list of dictionaries, where each dictionary contains:
    'title', 'link', 'published', and 'summary'.
    """
    url = "https://finance.yahoo.com/rss/topstories"
    news_items = []
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        print(f"Fetching RSS feed from: {url}")
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        print(f"RSS feed fetched successfully (status: {response.status_code}). Parsing...")
        feed = feedparser.parse(response.content)
        print(f"Found {len(feed.entries)} entries in RSS feed.")
        for entry in feed.entries:
            news_item = {
                "title": entry.get("title", "N/A"),
                "link": entry.get("link", "N/A"),
                "published": entry.get("published", "N/A"),
                "summary": entry.get("summary", "N/A")
            }
            news_items.append(news_item)
    except requests.exceptions.RequestException as e:
        print(f"Error fetching RSS feed: {e}")
    except Exception as e:
        print(f"Error parsing RSS feed: {e}")
    return news_items

def get_json_output_from_gemini(news_data: list[dict[str, str]]) -> str:
    """
    Sends news data to Google Gemini and asks for JSON structured output.
    """
    if not GOOGLE_API_KEY:
        return json.dumps({ "error": "Google API Key not configured." }, indent=2)
    if not news_data:
        return json.dumps({ "error": "No news data provided to Gemini." }, indent=2)

    # Create a new model instance
    model = genai.GenerativeModel('gemini-pro')

    prompt_news_items = []
    # Limiting to first 5 items for this integration step to keep API usage low and test quickly.
    # Increase this number (e.g., to 20) for more comprehensive processing later.
    items_to_process = news_data[:5]

    for item in items_to_process:
        prompt_news_items.append({
            "title": item.get("title"),
            "summary": item.get("summary")
        })

    prompt = (
        "You are a helpful assistant that processes news data and returns it in a structured JSON format.\n"
        "Below is a list of news items, each with a title and a summary.\n"
        "Please process these news items and return a single JSON array. Each object in the array should represent a news item and have the following keys:\n"
        "- \"headline\": The original title of the news article.\n"
        "- \"brief_summary\": A concise summary of the news item, generated by you based on the provided summary or title. Keep it to 1-2 sentences.\n"
        "IMPORTANT: Only return the JSON array itself, without any surrounding text, explanations, or markdown like ```json ... ```.\n"
        "Here is the news data:\n"
        f"{json.dumps(prompt_news_items)}\n\n"
        "JSON Output:"
    )

    try:
        print(f"Sending {len(items_to_process)} items to Gemini for processing...")
        response = model.generate_content(prompt)

        text_response = response.text
        print("Raw Gemini Response Text:", text_response) # Log raw response for debugging

        # Attempt to extract JSON from the response.
        # Gemini's response might include markdown ```json ... ``` tags or just ```
        if text_response.strip().startswith("```json"):
            text_response = text_response.strip()[7:-3].strip()
        elif text_response.strip().startswith("```"):
             text_response = text_response.strip()[3:-3].strip()

        gemini_output_list = json.loads(text_response)

        if not isinstance(gemini_output_list, list):
            print("Gemini output was not a list as expected. Wrapping in a list.")
            # This case might occur if Gemini returns a single object instead of an array for a single item.
            # Or if parsing failed to produce a list.
            # However, the prompt asks for an array. If it's not an array, something is wrong.
            # For robustness, we could wrap it, but it's better to understand why it's not a list.
            # For now, let's assume it should be a list as per prompt.
            raise ValueError("Gemini output after JSON parsing is not a list.")


        final_json_array = []
        for i, gemini_item in enumerate(gemini_output_list):
            if i < len(items_to_process):
                original_item = items_to_process[i] # Use items_to_process here
                final_item = {
                    "headline": gemini_item.get("headline", original_item.get("title")),
                    "source_url": original_item.get("link"),
                    "publication_date": original_item.get("published"),
                    "brief_summary": gemini_item.get("brief_summary", original_item.get("summary"))
                }
                final_json_array.append(final_item)
            else:
                print(f"Warning: Gemini returned more items ({len(gemini_output_list)}) than sent ({len(items_to_process)}). Ignoring extra items.")
                break

        if len(final_json_array) < len(items_to_process):
             print(f"Warning: Gemini returned fewer items ({len(final_json_array)}) than sent ({len(items_to_process)}). Some items might be missing.")


        return json.dumps(final_json_array, indent=2)

    except json.JSONDecodeError as e:
        print(f"Error decoding JSON from Gemini response: {e}")
        print(f"Problematic text: '{text_response}'")
        return json.dumps({"error": "Failed to decode JSON from Gemini", "details": str(e), "response_text": text_response}, indent=2)
    except Exception as e:
        print(f"Error interacting with Gemini: {e}")
        # Log the response text if available, in case of non-JSON-decode errors
        response_text_for_error = "N/A"
        if 'response' in locals() and hasattr(response, 'text'):
            response_text_for_error = response.text
        return json.dumps({"error": "Failed to process data with Gemini", "details": str(e), "response_text": response_text_for_error}, indent=2)


# Placeholder for Playwright function (not used for Yahoo RSS)
async def get_news_headlines_playwright(url: str) -> list[dict[str, str]]:
    print(f"Playwright scraping for {url} - (not actively used for Yahoo RSS).")
    await asyncio.sleep(0)
    return []


def main():
    print("Fetching news from Yahoo Finance RSS feed...")
    headlines_data = get_yahoo_finance_news_rss()

    if headlines_data:
        print(f"Found {len(headlines_data)} news items from RSS feed.")

        print("\nProcessing with Google Gemini...")
        # Send only a subset for testing Gemini integration (e.g., first 5)
        # The get_json_output_from_gemini function itself slices the data now.
        structured_json_output = get_json_output_from_gemini(headlines_data)
        print("\n--- Gemini Processed JSON Output ---")
        print(structured_json_output)
        print("--- End of Gemini Output ---")

    else:
        print("No news items found from RSS feed or an error occurred.")


if __name__ == "__main__":
    main()
